#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

PYTHON="${PYTHON:-python3}"

# Font ID generation: hashes the concatenated SHA-256 of the font header files
# for each family+size, folded into a signed 32-bit integer.
# Both NOTOSANS_* and ATKINSON_HN_* map to the same files, so they produce
# identical IDs — existing user settings (fontFamily == NOTOSANS == 1) and
# new settings (fontFamily == ATKINSON_HN == 2) resolve to the same font data.

$PYTHON - <<'PYEOF'
import hashlib, os, sys

def font_id(files):
    total = 0
    for f in files:
        h = hashlib.sha256(open(f, "rb").read()).digest()
        total += int.from_bytes(h, "big")
    return total % (2**32) - 2**31

defs = [
    ("NOTOSERIF_12", ["notoserif_12_regular.h", "notoserif_12_bold.h",
                      "notoserif_12_bolditalic.h", "notoserif_12_italic.h"]),
    ("NOTOSERIF_14", ["notoserif_14_regular.h", "notoserif_14_bold.h",
                      "notoserif_14_bolditalic.h", "notoserif_14_italic.h"]),
    ("NOTOSERIF_16", ["notoserif_16_regular.h", "notoserif_16_bold.h",
                      "notoserif_16_bolditalic.h", "notoserif_16_italic.h"]),
    ("NOTOSERIF_18", ["notoserif_18_regular.h", "notoserif_18_bold.h",
                      "notoserif_18_bolditalic.h", "notoserif_18_italic.h"]),
    ("ATKINSON_HN_12", ["atkinson_hn_12_regular.h", "atkinson_hn_12_bold.h",
                        "atkinson_hn_12_bolditalic.h", "atkinson_hn_12_italic.h"]),
    ("ATKINSON_HN_14", ["atkinson_hn_14_regular.h", "atkinson_hn_14_bold.h",
                        "atkinson_hn_14_bolditalic.h", "atkinson_hn_14_italic.h"]),
    ("ATKINSON_HN_16", ["atkinson_hn_16_regular.h", "atkinson_hn_16_bold.h",
                        "atkinson_hn_16_bolditalic.h", "atkinson_hn_16_italic.h"]),
    ("ATKINSON_HN_18", ["atkinson_hn_18_regular.h", "atkinson_hn_18_bold.h",
                        "atkinson_hn_18_bolditalic.h", "atkinson_hn_18_italic.h"]),
    ("UI_10", ["ubuntu_10_medium.h", "ubuntu_10_bold.h"]),
    ("UI_12", ["ubuntu_12_medium.h", "ubuntu_12_bold.h"]),
    ("SMALL", ["atkinson_hn_8_regular.h"]),
]

out = []
out.append("// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh")
out.append("#pragma once")
out.append("")

# NOTOSANS_* aliases to ATKINSON_HN_* (same font data)
out.append("// Atkinson Hyperlegible Next reader font (replaces NotoSans).")
out.append("// Both NOTOSANS_* and ATKINSON_HN_* map to the same files, so they produce")
out.append("// identical IDs — existing settings (fontFamily == NOTOSANS == 1) and")
out.append("// new settings (fontFamily == ATKINSON_HN == 2) resolve to the same font data.")

ahnd_values = {}
for name, files in defs:
    val = font_id(files)
    if name.startswith("ATKINSON_HN"):
        ahnd_values[name] = val
    out.append(f"#define {name}_FONT_ID ({val})")

# NOTOSANS aliases
out.append("")
for ahnd_name, ahnd_val in ahnd_values.items():
    nosans_name = ahnd_name.replace("ATKINSON_HN", "NOTOSANS")
    out.append(f"#define {nosans_name}_FONT_ID {ahnd_name}_FONT_ID")

out.append("")
out.append("// Font ID 0 is reserved as the \"not found\" sentinel.")
out.append("// Guard against any hash accidentally producing 0.")
out.append("// Font ID 0 is reserved as the \"not found\" sentinel.")
out.append("// Guard against any hash accidentally producing 0.")
for name, _ in defs:
    out.append(f"static_assert({name}_FONT_ID != 0, \"Font ID collision with sentinel\");")
for ahnd_name in ahnd_values:
    nosans_name = ahnd_name.replace("ATKINSON_HN", "NOTOSANS")
    out.append(f"static_assert({nosans_name}_FONT_ID != 0, \"Font ID collision with sentinel\");")

print("\n".join(out))
PYEOF

# Note: the heredoc above writes to stdout, which the caller captures.
# When run as a script, redirect to src/fontIds.h (caller handles this).
