#pragma once

#include <builtinFonts/notoserif_12_bold.h>
#include <builtinFonts/notoserif_12_bolditalic.h>
#include <builtinFonts/notoserif_12_italic.h>
#include <builtinFonts/notoserif_12_regular.h>
#include <builtinFonts/notoserif_14_bold.h>
#include <builtinFonts/notoserif_14_bolditalic.h>
#include <builtinFonts/notoserif_14_italic.h>
#include <builtinFonts/notoserif_14_regular.h>
#include <builtinFonts/notoserif_16_bold.h>
#include <builtinFonts/notoserif_16_bolditalic.h>
#include <builtinFonts/notoserif_16_italic.h>
#include <builtinFonts/notoserif_16_regular.h>
#include <builtinFonts/notoserif_18_bold.h>
#include <builtinFonts/notoserif_18_bolditalic.h>
#include <builtinFonts/notoserif_18_italic.h>
#include <builtinFonts/notoserif_18_regular.h>
#include <builtinFonts/atkinson_hn_8_regular.h>
#include <builtinFonts/atkinson_hn_12_bold.h>
#include <builtinFonts/atkinson_hn_12_bolditalic.h>
#include <builtinFonts/atkinson_hn_12_italic.h>
#include <builtinFonts/atkinson_hn_12_regular.h>
#include <builtinFonts/atkinson_hn_14_bold.h>
#include <builtinFonts/atkinson_hn_14_bolditalic.h>
#include <builtinFonts/atkinson_hn_14_italic.h>
#include <builtinFonts/atkinson_hn_14_regular.h>
#include <builtinFonts/atkinson_hn_16_bold.h>
#include <builtinFonts/atkinson_hn_16_bolditalic.h>
#include <builtinFonts/atkinson_hn_16_italic.h>
#include <builtinFonts/atkinson_hn_16_regular.h>
#include <builtinFonts/atkinson_hn_18_bold.h>
#include <builtinFonts/atkinson_hn_18_bolditalic.h>
#include <builtinFonts/atkinson_hn_18_italic.h>
#include <builtinFonts/atkinson_hn_18_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_medium.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_medium.h>
